### ISSUE TITLE
Topics for Improvement

### ISSUE THREAD

**Issue by Enbji** [mcleung/LaserHarp#1]
@mcleung 
Constructing Box
Step 2: can you show me what this notch looks like?
Steps 4-6: maybe an Ikea style diagram showing how these go together? I know what the final looks like but it may not be intuitive to everyone

Constructing Lasers:
Step 1: Do you have a measurement for what "evenly spaced" is?
            Perhaps a 2D labeled diagram of all the parts and how they are put together?

Step 2: Diagrams, Diagrams! This may make alignment unnecessary if things are properly spaced out.

Step 4: What diagram? I dont seee itt?!?

**Comment by Enbji** [comment]
@mcleung 
Assembly Instructions:
From what I see of the cross-bar there is a difference between what you have constructed here (connection pieces on the top bar rather then on the upright bars shown in the cad image from earlier)

Otherwise these instructions looks a lot better. I like the step by step instructions to show how it all works, if  you had something similar for the construction file it would be worth a lot.

**Comment by mcleu** [comment]
Have been addressed in #2 .
Closing for now.
